// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Events struct {
	ID         int32
	Name       string
	UserID     string
	CreatedAt  pgtype.Timestamptz
	InsertedAt pgtype.Timestamptz
}

type Food struct {
	ID             int32
	Name           string
	TypeID         int32
	IntakeStatusID int32
	FeederID       int32
	LocationID     int32
	Remarks        pgtype.Text
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	RemovedAt      pgtype.Timestamptz
}

type FoodFeeders struct {
	ID        int32
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type FoodIntakeStatus struct {
	ID        int32
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type FoodLocations struct {
	ID        int32
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type FoodTypes struct {
	ID        int32
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type UserTypes struct {
	ID        int32
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Users struct {
	ID        int32
	Username  string
	TypeID    int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	RemovedAt pgtype.Timestamptz
}
