// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"context"
)

type Querier interface {
	CheckFoodIsRemoved(ctx context.Context, id int32) (bool, error)
	CheckUserIsExisting(ctx context.Context, username string) (bool, error)
	CreateEvent(ctx context.Context, arg []CreateEventParams) (int64, error)
	CreateFood(ctx context.Context, arg CreateFoodParams) error
	DeleteFood(ctx context.Context, id int32) (int64, error)
	GetFood(ctx context.Context, id int32) (GetFoodRow, error)
	ListFood(ctx context.Context, arg ListFoodParams) ([]ListFoodRow, error)
	ListUsers(ctx context.Context) ([]string, error)
	UpdateFood(ctx context.Context, arg UpdateFoodParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
