// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: food.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFood = `-- name: CreateFood :exec
insert into food (
    name, type, intake_status, feeder, location, remarks
) values (
    $1, $2, $3, $4, $5, $6
)
`

type CreateFoodParams struct {
	Name         string      `db:"name"`
	Type         int32       `db:"type"`
	IntakeStatus int32       `db:"intake_status"`
	Feeder       int32       `db:"feeder"`
	Location     int32       `db:"location"`
	Remarks      pgtype.Text `db:"remarks"`
}

func (q *Queries) CreateFood(ctx context.Context, arg *CreateFoodParams) error {
	_, err := q.db.Exec(ctx, createFood,
		arg.Name,
		arg.Type,
		arg.IntakeStatus,
		arg.Feeder,
		arg.Location,
		arg.Remarks,
	)
	return err
}
