// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Food struct {
	ID             int32              `db:"id"`
	Name           string             `db:"name"`
	TypeID         int32              `db:"type_id"`
	IntakeStatusID int32              `db:"intake_status_id"`
	FeederID       int32              `db:"feeder_id"`
	LocationID     int32              `db:"location_id"`
	Remarks        pgtype.Text        `db:"remarks"`
	CreatedAt      pgtype.Timestamptz `db:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at"`
}

type FoodFeeders struct {
	ID        int32              `db:"id"`
	Name      string             `db:"name"`
	CreatedAt pgtype.Timestamptz `db:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at"`
}

type FoodIntakeStatus struct {
	ID        int32              `db:"id"`
	Name      string             `db:"name"`
	CreatedAt pgtype.Timestamptz `db:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at"`
}

type FoodLocations struct {
	ID        int32              `db:"id"`
	Name      string             `db:"name"`
	CreatedAt pgtype.Timestamptz `db:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at"`
}

type FoodTypes struct {
	ID        int32              `db:"id"`
	Name      string             `db:"name"`
	CreatedAt pgtype.Timestamptz `db:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at"`
}
