// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Food struct {
	ID           int32              `db:"id"`
	Name         string             `db:"name"`
	Type         int32              `db:"type"`
	IntakeStatus int32              `db:"intake_status"`
	Feeder       int32              `db:"feeder"`
	Location     int32              `db:"location"`
	Remarks      pgtype.Text        `db:"remarks"`
	CreatedAt    pgtype.Timestamptz `db:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at"`
}
