// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package dbgen

import (
	"context"
)

type Querier interface {
	CreateFood(ctx context.Context, arg *CreateFoodParams) error
}

var _ Querier = (*Queries)(nil)
