// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package dbgen

import (
	"context"
)

type Querier interface {
	CreateFood(ctx context.Context, arg *CreateFoodParams) error
	GetFood(ctx context.Context, id int32) (GetFoodRow, error)
	ListFood(ctx context.Context, arg *ListFoodParams) ([]ListFoodRow, error)
}

var _ Querier = (*Queries)(nil)
