recursive: true
filename: "mock_{{ .InterfaceName | snakecase }}.go"
outpkg: "mock{{ .PackageName }}"

packages:
  github.com/gatsu420/mary/db/repository:
    config:
      include-regex: "Querier"
      dir: "./mocks/db/repository"

  github.com/gatsu420/mary/app/usecases/food:
    config:
      include-regex: "Usecase"
      dir: "./mocks/app/usecases/food"

  github.com/gatsu420/mary/app/usecases/users:
    config:
      include-regex: "Usecase"
      dir: "./mocks/app/usecases/users"

  github.com/gatsu420/mary/auth:
    config:
      include-regex: "Auth"
      dir: "./mocks/auth"
