recursive: true
filename: "mock_{{ .InterfaceName | snakecase }}.go"
outpkg: "mock{{ .PackageName }}"

packages:
  github.com/gatsu420/mary/app/repository:
    config:
      include-regex: "Querier"
      dir: "./mocks/app/repository"

  github.com/gatsu420/mary/app/cache:
    config:
      include-regex: "Storer"
      dir: "./mocks/app/cache"

  github.com/gatsu420/mary/app/usecases/food:
    config:
      include-regex: "Usecase"
      dir: "./mocks/app/usecases/food"

  github.com/gatsu420/mary/app/usecases/users:
    config:
      include-regex: "Usecase"
      dir: "./mocks/app/usecases/users"

  github.com/gatsu420/mary/app/usecases/events:
    config:
      include-regex: "Usecase"
      dir: "./mocks/app/usecases/events"

  github.com/gatsu420/mary/app/auth:
    config:
      include-regex: "Auth"
      dir: "./mocks/app/auth"
