// Code generated by mockery v2.53.3. DO NOT EDIT.

package mockfood

import (
	context "context"

	food "github.com/gatsu420/mary/app/usecases/food"
	mock "github.com/stretchr/testify/mock"

	repository "github.com/gatsu420/mary/db/repository"
)

// MockUsecases is an autogenerated mock type for the Usecases type
type MockUsecases struct {
	mock.Mock
}

type MockUsecases_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsecases) EXPECT() *MockUsecases_Expecter {
	return &MockUsecases_Expecter{mock: &_m.Mock}
}

// CheckFoodIsRemoved provides a mock function with given fields: ctx, id
func (_m *MockUsecases) CheckFoodIsRemoved(ctx context.Context, id int32) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for CheckFoodIsRemoved")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUsecases_CheckFoodIsRemoved_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckFoodIsRemoved'
type MockUsecases_CheckFoodIsRemoved_Call struct {
	*mock.Call
}

// CheckFoodIsRemoved is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockUsecases_Expecter) CheckFoodIsRemoved(ctx interface{}, id interface{}) *MockUsecases_CheckFoodIsRemoved_Call {
	return &MockUsecases_CheckFoodIsRemoved_Call{Call: _e.mock.On("CheckFoodIsRemoved", ctx, id)}
}

func (_c *MockUsecases_CheckFoodIsRemoved_Call) Run(run func(ctx context.Context, id int32)) *MockUsecases_CheckFoodIsRemoved_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockUsecases_CheckFoodIsRemoved_Call) Return(_a0 error) *MockUsecases_CheckFoodIsRemoved_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUsecases_CheckFoodIsRemoved_Call) RunAndReturn(run func(context.Context, int32) error) *MockUsecases_CheckFoodIsRemoved_Call {
	_c.Call.Return(run)
	return _c
}

// CreateFood provides a mock function with given fields: ctx, arg
func (_m *MockUsecases) CreateFood(ctx context.Context, arg *food.CreateFoodParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateFood")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *food.CreateFoodParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUsecases_CreateFood_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFood'
type MockUsecases_CreateFood_Call struct {
	*mock.Call
}

// CreateFood is a helper method to define mock.On call
//   - ctx context.Context
//   - arg *food.CreateFoodParams
func (_e *MockUsecases_Expecter) CreateFood(ctx interface{}, arg interface{}) *MockUsecases_CreateFood_Call {
	return &MockUsecases_CreateFood_Call{Call: _e.mock.On("CreateFood", ctx, arg)}
}

func (_c *MockUsecases_CreateFood_Call) Run(run func(ctx context.Context, arg *food.CreateFoodParams)) *MockUsecases_CreateFood_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*food.CreateFoodParams))
	})
	return _c
}

func (_c *MockUsecases_CreateFood_Call) Return(_a0 error) *MockUsecases_CreateFood_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUsecases_CreateFood_Call) RunAndReturn(run func(context.Context, *food.CreateFoodParams) error) *MockUsecases_CreateFood_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteFood provides a mock function with given fields: ctx, id
func (_m *MockUsecases) DeleteFood(ctx context.Context, id int32) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFood")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUsecases_DeleteFood_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFood'
type MockUsecases_DeleteFood_Call struct {
	*mock.Call
}

// DeleteFood is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockUsecases_Expecter) DeleteFood(ctx interface{}, id interface{}) *MockUsecases_DeleteFood_Call {
	return &MockUsecases_DeleteFood_Call{Call: _e.mock.On("DeleteFood", ctx, id)}
}

func (_c *MockUsecases_DeleteFood_Call) Run(run func(ctx context.Context, id int32)) *MockUsecases_DeleteFood_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockUsecases_DeleteFood_Call) Return(_a0 error) *MockUsecases_DeleteFood_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUsecases_DeleteFood_Call) RunAndReturn(run func(context.Context, int32) error) *MockUsecases_DeleteFood_Call {
	_c.Call.Return(run)
	return _c
}

// GetFood provides a mock function with given fields: ctx, id
func (_m *MockUsecases) GetFood(ctx context.Context, id int32) (repository.GetFoodRow, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetFood")
	}

	var r0 repository.GetFoodRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (repository.GetFoodRow, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) repository.GetFoodRow); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(repository.GetFoodRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecases_GetFood_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFood'
type MockUsecases_GetFood_Call struct {
	*mock.Call
}

// GetFood is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockUsecases_Expecter) GetFood(ctx interface{}, id interface{}) *MockUsecases_GetFood_Call {
	return &MockUsecases_GetFood_Call{Call: _e.mock.On("GetFood", ctx, id)}
}

func (_c *MockUsecases_GetFood_Call) Run(run func(ctx context.Context, id int32)) *MockUsecases_GetFood_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockUsecases_GetFood_Call) Return(_a0 repository.GetFoodRow, _a1 error) *MockUsecases_GetFood_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecases_GetFood_Call) RunAndReturn(run func(context.Context, int32) (repository.GetFoodRow, error)) *MockUsecases_GetFood_Call {
	_c.Call.Return(run)
	return _c
}

// ListFood provides a mock function with given fields: ctx, arg
func (_m *MockUsecases) ListFood(ctx context.Context, arg *food.ListFoodParams) ([]repository.ListFoodRow, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListFood")
	}

	var r0 []repository.ListFoodRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *food.ListFoodParams) ([]repository.ListFoodRow, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *food.ListFoodParams) []repository.ListFoodRow); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.ListFoodRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *food.ListFoodParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsecases_ListFood_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFood'
type MockUsecases_ListFood_Call struct {
	*mock.Call
}

// ListFood is a helper method to define mock.On call
//   - ctx context.Context
//   - arg *food.ListFoodParams
func (_e *MockUsecases_Expecter) ListFood(ctx interface{}, arg interface{}) *MockUsecases_ListFood_Call {
	return &MockUsecases_ListFood_Call{Call: _e.mock.On("ListFood", ctx, arg)}
}

func (_c *MockUsecases_ListFood_Call) Run(run func(ctx context.Context, arg *food.ListFoodParams)) *MockUsecases_ListFood_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*food.ListFoodParams))
	})
	return _c
}

func (_c *MockUsecases_ListFood_Call) Return(_a0 []repository.ListFoodRow, _a1 error) *MockUsecases_ListFood_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsecases_ListFood_Call) RunAndReturn(run func(context.Context, *food.ListFoodParams) ([]repository.ListFoodRow, error)) *MockUsecases_ListFood_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateFood provides a mock function with given fields: ctx, arg
func (_m *MockUsecases) UpdateFood(ctx context.Context, arg *food.UpdateFoodParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateFood")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *food.UpdateFoodParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUsecases_UpdateFood_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateFood'
type MockUsecases_UpdateFood_Call struct {
	*mock.Call
}

// UpdateFood is a helper method to define mock.On call
//   - ctx context.Context
//   - arg *food.UpdateFoodParams
func (_e *MockUsecases_Expecter) UpdateFood(ctx interface{}, arg interface{}) *MockUsecases_UpdateFood_Call {
	return &MockUsecases_UpdateFood_Call{Call: _e.mock.On("UpdateFood", ctx, arg)}
}

func (_c *MockUsecases_UpdateFood_Call) Run(run func(ctx context.Context, arg *food.UpdateFoodParams)) *MockUsecases_UpdateFood_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*food.UpdateFoodParams))
	})
	return _c
}

func (_c *MockUsecases_UpdateFood_Call) Return(_a0 error) *MockUsecases_UpdateFood_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUsecases_UpdateFood_Call) RunAndReturn(run func(context.Context, *food.UpdateFoodParams) error) *MockUsecases_UpdateFood_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUsecases creates a new instance of MockUsecases. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsecases(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsecases {
	mock := &MockUsecases{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
