// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: auth.sql

package repository

import (
	"context"
)

const checkUserIsExisting = `-- name: CheckUserIsExisting :one
select
    username is not null::bool as is_existing
from users
where username = $1
`

func (q *Queries) CheckUserIsExisting(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserIsExisting, username)
	var is_existing bool
	err := row.Scan(&is_existing)
	return is_existing, err
}
