// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: auth.sql

package repository

import (
	"context"
)

const checkUserIsExisting = `-- name: CheckUserIsExisting :one
select exists (
    select 1 from users
    where username = $1
)
`

func (q *Queries) CheckUserIsExisting(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserIsExisting, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
