// Code generated by mockery v2.53.3. DO NOT EDIT.

package mockevents

import (
	context "context"

	events "github.com/gatsu420/mary/app/usecases/events"
	mock "github.com/stretchr/testify/mock"
)

// MockUsecase is an autogenerated mock type for the Usecase type
type MockUsecase struct {
	mock.Mock
}

type MockUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsecase) EXPECT() *MockUsecase_Expecter {
	return &MockUsecase_Expecter{mock: &_m.Mock}
}

// CreateEvent provides a mock function with given fields: ctx, arg
func (_m *MockUsecase) CreateEvent(ctx context.Context, arg *events.CreateEventParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *events.CreateEventParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUsecase_CreateEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEvent'
type MockUsecase_CreateEvent_Call struct {
	*mock.Call
}

// CreateEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - arg *events.CreateEventParams
func (_e *MockUsecase_Expecter) CreateEvent(ctx interface{}, arg interface{}) *MockUsecase_CreateEvent_Call {
	return &MockUsecase_CreateEvent_Call{Call: _e.mock.On("CreateEvent", ctx, arg)}
}

func (_c *MockUsecase_CreateEvent_Call) Run(run func(ctx context.Context, arg *events.CreateEventParams)) *MockUsecase_CreateEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*events.CreateEventParams))
	})
	return _c
}

func (_c *MockUsecase_CreateEvent_Call) Return(_a0 error) *MockUsecase_CreateEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUsecase_CreateEvent_Call) RunAndReturn(run func(context.Context, *events.CreateEventParams) error) *MockUsecase_CreateEvent_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUsecase creates a new instance of MockUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsecase {
	mock := &MockUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
